# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.

env:
  GITHUB_CONTEXT: ${{ toJson(github) }}

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
      - release/**
      - test

  pull_request:
    types:
      - opened
      - synchronize

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-10.15

    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: echo branch
        if: github.event_name == 'push'
        run: |
          echo On push
          echo ${GITHUB_REF##*/}
          echo ${{ github.head_ref }}
          echo ${{ github.event_name }}

      - name: Dump GitHub context
        if: github.event_name == 'pull_request'
        run: |
          echo On Pull Request
          echo ${{ github.event.pull_request.head.ref }}
          echo ${{ github.head_ref }}
          echo ${{ github.event_name }}

      # - name: Set up Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: ${{ matrix.node-version }}
      #
      # - name: Install dependencies
      #   run: npm i
      #
      # - name: Run the Test
      #   run: npm test -- --coverage
      #
      # - name: Build
      #   run: npm build

      # # Runs a set of commands using the runners shell
      # - name: Run a multi-line script
      #   run: |
      #     echo Add other actions to build,
      #     echo test, and deploy your project.
